strictness: veryhigh
test-warnings: true
doc-warnings: false

ignore-paths:
  - .git
  - .tox
  - venv
uses:
  - django
pep8:
  run: false

pylint:
  options:
    max-line-length: 120
    good-names: pk, e, T, by, urlpatterns, do
    generated-members: query
